### ISSUE TITLE
Packer fails on ssh

### ISSUE THREAD

**Issue by nnewc** [David-VTUK/Rancher-Packer#27]
I may be dong something wrong, but when I run the examples on my vsphere cluster, the template comes up with SSH after some time but credentials don't work. After some time, it starts the installer (see screenshot below). 

I have tried with ubuntu 20, ubuntu22, and centos7 and all seem to have issues logging in:
```bash
Nathans-MBP:src nathannewcomb$ ssh ubuntu@10.7.2.195
The authenticity of host '10.7.2.195 (10.7.2.195)' can't be established.
ED25519 key fingerprint is SHA256:/1TIyb0py4KHagmPabNGdLepMH+98B9tkeIqxPZOYKE.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.7.2.195' (ED25519) to the list of known hosts.
ubuntu@10.7.2.195's password:
```

![image](https://user-images.githubusercontent.com/76885214/213284405-16d5f42f-fffd-4738-ad70-0e9e4cd25a23.png)

**Comment by David-VTUK** [comment]
Can you post the entire packer log output please? The username for the completed template will be `packerbuilt`

Is that screenshot of the template being created?  If so, It looks like it hasn't ingested the auto install config which is delivered by packer spinning up an ad hoc webserver on the machine you're running packer on, so the VM that gets created needs connectivity back to that machine.

**Comment by nnewc** [comment]
So I think you are right. My problem is I'm connecting to vSphere through a VPN and need my VPN IP instead of my laptop IP:

`==> ubuntu-2004: HTTP server is working at http://10.0.40.151:8469/`

How do I specify that in Packer?

**Comment by David-VTUK** [comment]
You should be able to set it with [http_ip](https://developer.hashicorp.com/packer/plugins/builders/vsphere/vsphere-iso#http_ip) or set it directly in this line, replacing `HTTPIP` https://github.com/David-VTUK/Rancher-Packer/blob/d6e4c9215d998c9e31b902cfd0a61563c23821d5/vSphere/ubuntu_2004/ubuntu-2004.json#L42

**Comment by nnewc** [comment]
I think this should fix it. I'm just trying to figure out how to do this on my VPN connection to vSphere.

**Comment by David-VTUK** [comment]
You could host the cloud-init files on a external web server that your VM will have access to and modify the autoinstall string to explicitly reference it.

Sounds like you're already working on the config - I'll close this for now.
