### ISSUE TITLE
SUSE SLES Image

### ISSUE THREAD

**Issue by picoroma** [David-VTUK/Rancher-Packer#8]
Hi! Any tips to build a SLES 15 image for Rancher?
Have you planning to release a script\config for this kind of OS ?
THX
P.

**Comment by smangelkramer** [comment]
Hi @picoroma good idea. I just created an SLE 15 SP2 image for use in vSphere as Rancher / RKE node.

```
SUSEConnect --product PackageHub/15.2/x86_64
SUSEConnect --product sle-module-public-cloud/15.2/x86_64
sudo zypper install cloud-init open-vm-tools

systemctl enable cloud-init-local.service
systemctl enable cloud-init.service
systemctl enable cloud-config.service
systemctl enable cloud-final.service
systemctl daemon-reload

SUSEConnect --product sle-module-containers/15.2/x86_64 
sudo zypper install docker & sudo systemctl enable docker.service 

for port in 80/tcp 443/tcp 2376/tcp 2379/tcp 2380/tcp 6443/tcp 9099/tcp 9796/tcp 10250/tcp 10254/tcp 30000-32767/tcp 8472/udp 30000-32767/udp
do
    sudo firewall-cmd --zone=public --permanent --add-port=$port
done

swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

sudo truncate -s 0 /etc/machine-id
sudo rm /var/lib/dbus/machine-id 
sudo ln -s /etc/machine-id /var/lib/dbus/machine-id 

sed -i 's/#AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config 

cloud-init clean -s -l
```

Perhaps this is useful for you - and or  @David-VTUK. Best Sebastian

**Comment by picoroma** [comment]
Hi Sebastian. THX for sharing.
Unfortunately I do not have a properly vSphere Enviroment to test it. I'm having a lot of problem with Ubuntu too.
Anyway, as per my experience with vSphere\VmWare templates - and accordingly with this:
https://www.suse.com/support/kb/doc/?id=000019336
Is necessary to remove some .xml file in order to avoid that all the VMs created starting from the same Template - have ALL the same IP addresses, and cause problem with DHCP.
Please add a command like: 
rm /var/lib/wicked/*.xml
just after:
"sudo ln -s /etc/machine-id /var/lib/dbus/machine-i"
P.

**Comment by picoroma** [comment]
Hi @smangelkramer ,
th file you posted is intended to use as "script.sh" file, right ?
But what about the preseed.cfg and .json file ?
Can be used the same file used for Ubuntu ?
If not, how can be adapted for SLES 15 ?
THX
P.

**Comment by smangelkramer** [comment]
Hi @picoroma ,

these commands are just the OS preparation for use with Rancher / RKE.
AFAIK SUSE has no support for pressed (debian and ubuntu does, ubuntu now uses "autoinstall"),
RedHat/CentOS uses "KickStart" and SUSE  use "AutoYAST".

What exactly do you want to achieve ? Build an SUSE OS Image with Packer?

Best,
Sebastian

**Comment by picoroma** [comment]
Yes, exactly.But I do not find documents on how to achieve this.Like the template you can build for rancher with ubuntu or rhel or centos....(Described in this project)But no info about build a Suse Sles Template for vSphere....Il 26 feb 2021 20:14, Sebastian Mangelkramer <notifications@github.com> ha scritto:
Hi @picoroma ,
these commands are just the OS preparation for use with Rancher / RKE.
AFAIK SUSE has no support for pressed (debian and ubuntu does, ubuntu now uses "autoinstall"),
RedHat/CentOS uses "KickStart" and SUSE  use "AutoYAST".
What exactly do you want to achieve ? Build an SUSE OS Image with Packer?
Best,
Sebastian

**Comment by yankcrime** [comment]
It's not SLES, but [this PR](https://github.com/David-VTUK/Rancher-Packer/pull/9) provides the config for building a compatible openSUSE Leap 15 image.
